version: "3"
services:
  grafana:

    container_name: grafana
    image: grafana/grafana-enterprise:10.2.2-boringcrypto
    volumes:
      - ./data/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 127.0.0.1:3000:3000
    restart: always
    networks:
      - traefik_default
      - net

networks:
  traefik_default:
    external: true
  net: