
http:
  middlewares:
    redirect-to-https:
      redirectscheme:
        scheme: https
  routers:
#    traefik-api:
#      middlewares: traefik-basic-auth
#      rule: Host(`traefik-dashboard.homeinfra.org`)
#      service: api@internal
#      entrypoints: web

    http_to_https:
      entrypoints: web
      middlewares: redirect-to-https
      priority: 1
      rule: HostRegexp(`{catchall:.*}`)
      service: noop@internal

