http:
  routers:
    docker_gitea:
      entrypoints: websecure
      rule: Host(`git.homeinfra.org`)
      service: docker_gitea
      tls:
        certresolver: cloudflare
  services:
    docker_gitea:
      loadbalancer:
        servers:
          - url: http://gitea:3000

tcp:
  routers:
    gitea-ssh:
      rule: HostSNI(`*`)
      entrypoints: gitssh
      service: gitea-ssh
  services:
    gitea-ssh:
      loadbalancer:
        servers:
          - address: gitea:22


