http:
  routers:
    grafana:
      entrypoints: websecure
      rule: Host(`grafana.homeinfra.org`)
      service: grafana
      tls:
        certresolver: cloudflare
  services:
    grafana:
      loadbalancer:
        servers:
          - url: http://grafana:3000
