http:
  routers:
    homepage:
      entrypoints: websecure
      rule: Host(`www.homeinfra.org`) || Host(`homeinfra.org`)
      service: homepage
      tls:
        certresolver: cloudflare
  services:
    homepage:
      loadbalancer:
        servers:
          - url: http://homepage:80
