http:
  routers:
    docker_portainer:
      entrypoints: websecure
      rule: Host(`portainer.homeinfra.org`)
      service: docker_portainer
      tls:
        certresolver: cloudflare
  services:
    docker_portainer:
      loadbalancer:
        servers:
          - url: http://portainer:9000
