version: "2"
services:
  web:
    restart: always
    image: traefik:v2.9.7
    container_name: traefik
    networks:
      - traefik_default
      - net
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
      # - "8080:8080"
    command:
      - "--configFile=/conf/traefik.yml"
    environment:
      - "CLOUDFLARE_DNS_API_TOKEN=${CLOUDFLARE_DNS_API_TOKEN}"
      - "TZ=Asia/Shanghai"
    volumes:
      - ./conf:/conf:ro
      - "./data/letsencrypt:/letsencrypt"
      - ./data/traefik_logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

networks:
  net:
    driver: bridge

  traefik_default:
    external: true

    

